- hosts: master
  become: true
  tasks:

    - name: Unmount /var/lib/kubelet if mounted
      shell: |
        if mountpoint -q /var/lib/kubelet; then
          fuser -k /var/lib/kubelet || true
          umount /var/lib/kubelet || true
        fi
      register: unmount_kubelet
      ignore_errors: true

    - name: Stop kubelet and containerd services
      service:
        name: "{{ item }}"
        state: stopped
      loop:
        - kubelet
        - containerd
      ignore_errors: true

    - name: Run kubeadm reset to reset the cluster
      command: kubeadm reset -f
      ignore_errors: true

    - name: Kill any remaining Kubernetes-related processes
      shell: |
        pkill -f kubelet
        pkill -f kube-apiserver
        pkill -f etcd
      ignore_errors: true

    - name: Clean up Kubernetes configuration directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kubernetes
        - /var/lib/etcd
        - /var/lib/kubelet
        - /var/lib/cni
        - /etc/cni/net.d
      ignore_errors: true

    - name: Restart containerd service to clear any leftover state
      service:
        name: containerd
        state: restarted
      ignore_errors: true

    - name: Flush iptables rules for Kubernetes ports
      shell: |
        iptables -D INPUT -p tcp --dport 6443 -j ACCEPT || true
        iptables -D INPUT -p tcp --dport 2379 -j ACCEPT || true
        iptables -D INPUT -p tcp --dport 2380 -j ACCEPT || true
        iptables -D INPUT -p tcp --dport 10250 -j ACCEPT || true
        iptables -D INPUT -p tcp --dport 10251 -j ACCEPT || true
        iptables -D INPUT -p tcp --dport 10252 -j ACCEPT || true
      args:
        executable: /bin/bash

    - name: Clear any IP forwarding changes
      sysctl:
        name: net.ipv4.ip_forward
        value: '0'
        sysctl_set: no  # Ensure this is temporary
