name: Lint Go Code

on:
  push:
    branches:
      - "**"   # Runs on all branches
  pull_request:
    branches:
      - "**"   # Runs on all PRs

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./go-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2  # Use the latest stable version
          working-directory: ./go-backend

      - name: Run golangci-lint
        run: golangci-lint run --out-format=github-actions --timeout=5m