name: Next.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./next-frontend

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Set up environment variables
        run:  |
          touch .env.docker
          # Populate .env.docker for Frontend
          echo "NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}" >> .env.docker
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

