name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python_scripts

    steps:
      # Check out the code from the repository
      - uses: actions/checkout@v4

      # Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run unit tests using unittest, with discovery in the 'python_scripts/tests' directory
      - name: Run tests
        run: python -m unittest discover -s tests
